---

- hosts: all
  become: true
  pre_tasks:
  
  - name: apt update
    apt:
      update_cache: yes
      force_apt_get: yes
      cache_valid_time: 3600

  - name: apt upgrade
    apt:
      upgrade: dist

  - name: remove old packages and clean cache
    apt:
      autoremove: yes
      autoclean: yes
      clean: yes

- hosts: all
  become: true
  vars_files: 
    - /ansible_collections/elsternet/cloudwerkstatt/roles/local_accounts/vars/main.yml
  tasks:
    - name: Include a role from a local collection
      ansible.builtin.import_role:
        name: elsternet.cloudwerkstatt.local_accounts

    - name: Configure SSH
      ansible.builtin.import_role:
        name: elsternet.cloudwerkstatt.ssh_config
  
